name: Continuous Integration
on:
    pull_request:
        types: [opened, synchronize, reopened]
    push:
        branches:
            - master

jobs:
    report:
        name: Report
        runs-on: ubuntu-latest
        steps:
            - name: ref
              run: echo ${{ github.ref }}
            - name: event_name
              run: echo ${{ github.event_name }}
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v1
            - name: setup node
              uses: actions/setup-node@v1
              with:
                  node-version: "16.x"
            - name: install
              run: npm install
            - name: build
              run: npm run build
            - name: coverage
              run: npm run coverage
            - name: Upload coverage to Codecov
              if: github.event_name == 'push' && endsWith(github.ref,'/master')
              uses: codecov/codecov-action@v1.0.2
              with:
                  token: ${{secrets.CODECOV_TOKEN}}
    publish:
        name: Publish
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: checkout
              if: github.event_name == 'create' && startsWith(github.ref,'refs/tags/')
              uses: actions/checkout@v1
            - name: setup node
              if: github.event_name == 'create' && startsWith(github.ref,'refs/tags/')
              uses: actions/setup-node@v1
              with:
                  node-version: "16.x"
                  registry-url: "https://registry.npmjs.org"
            - name: install
              run: npm install
            - name: deploy
              if: github.event_name == 'create' && startsWith(github.ref,'refs/tags/')
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
